### ISSUE TITLE
Не приходят оплаченные заказы на почту

### ISSUE THREAD

**Issue by themygit** [fidals/shopelectro#585] opened 2018-09-21 08:36 UTC
https://prnt.sc/kwtnid от 19 числа. на почту не приходил

**Comment by duker33** [comment] 2018-09-21 08:54
we have fake ids, so `8062 == 14062`

**Comment by duker33** [comment] 2018-09-21 08:57
Artemiy improved and monitored logs at https://github.com/fidals/shopelectro/issues/561
We send mails in all cases. So, the problem is in some mail side.

Currently i have no idea how we can debug it. But i'll try in some way

**Comment by themygit** [comment] 2018-09-21 09:34
Не дошел заказ 8095
и в почте 3 заказа, 4 потеряли, а метрика показывает 1 продажу

**Comment by themygit** [comment] 2018-09-24 10:42
не дошел 8103
@duker33 есть идеи почему ?
моя теория с шаблонами и некорректным заполнением - лажа ?

**Comment by duker33** [comment] 2018-10-17 13:43
it's hard task, that requires devops skills. So, `x2`

**Comment by duker33** [comment] 2018-10-17 14:14
we can test email sending with vanilla django mech:
https://docs.djangoproject.com/en/2.1/topics/testing/tools/#email-services

**Comment by duker33** [comment] 2018-10-17 14:31
we had problems with this two orders:
https://www.shopelectro.ru/admin/shopelectro/order/7833/change/?_changelist_filters=p%3D6%26q%3D
https://www.shopelectro.ru/admin/shopelectro/order/8103/change/?_changelist_filters=p%3D4%26q%3D

Both this cases went from Ya.Kassa. I'll try to cover them with tests in this task and close it

**Comment by duker33** [comment] 2018-10-23 14:10
found it in selenium section.
Task is resolved by https://github.com/fidals/shopelectro/pull/602

**Closed** 2018-10-23 14:10 UTC
Labels: 1, 1 hour, bug, devops, from PO, hard, x2
